### ISSUE TITLE
Provide real world example

### ISSUE THREAD

**Issue by roll** [okfn/datapackage-bigquery-py#2]
Add a little demo version.

**Comment by roll** [comment]
@pwalsh 
could you point me to a proper datapackage?

**Comment by pwalsh** [comment]
@roll Sure:

https://github.com/openspending/fiscal-data-package-demos/tree/master/boost-moldova

Or any others https://github.com/openspending/fiscal-data-package-demos and there are also some https://github.com/os-data if you need more.

**Comment by roll** [comment]
@pwalsh thanks

**Comment by danfowler** [comment]
@roll see here for more generic (not only Fiscal) data packages: https://github.com/datasets/

**Comment by roll** [comment]
thanks @danfowler =)

**Comment by roll** [comment]
CLOSED in favor of https://github.com/okfn/datapackage-sql-py/issues/2 because this repository is just a mirror for BigQuery
