### ISSUE TITLE
BigQuery's table names must be alphanumeric plus _ and $ only

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-bigquery-py#6]
> [Required] The ID of the table. The ID must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_). The maximum length is 1,024 characters.
> https://cloud.google.com/bigquery/docs/reference/v2/tables

We don't do this validation on our side, and if a resource file name isn't valid according to these criteria, the import won't work.

**Comment by roll** [comment]
FIXED
